services:
  - type: web
    name: instagram-oauth-test
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: fastapi run app/main.py --host 0.0.0.0 --port 80